### ISSUE TITLE
Timestamps are shown incorrectly

### ISSUE THREAD

**Issue by janos-felfel** [felfel/logging-py#11]
Timestamps are given in utc time but with the offset for zurich time.

A message that was generated at 11:35 utc = 13:35 zurich time gets the following wrong timestamp:
`2018-10-05 11:35:41.131804+02:00`

**Comment by benelot** [comment]
That is so awkward. I had this on some days and not on other days. I once fixed it when I had it and it did work again, but it seems I did not solve it properly. So sorry...

**Comment by janos-felfel** [comment]
No worries :-)

**Comment by fahyik** [comment]
I believe this is fixed in 0.3.16.
